User Logic

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,10 +4,10 @@
 
 echo "Hello! kid. I'm the Goofy 🐶 and I'm responsible for all your coding standards. Woof..."
 
-yarn format:check || (
-    echo "Woof... 🐶 You got caught.👻 Prettier Check failed. Run yarn format, add changes and try commit again.";
-    false;
-)
+#yarn format:check || (
+#    echo "Woof... 🐶 You got caught.👻 Prettier Check failed. Run yarn format, add changes and try commit again.";
+#    false;
+#)
 
 echo "Hey kiddo, Formatting looks good. Woof... 🐶"
 #
